# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"P\n\x10TelemetryRequest\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x14\n\x0csensor_value\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"#\n\x11TelemetryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2W\n\tTelemetry\x12J\n\rSendTelemetry\x12\x1b.telemetry.TelemetryRequest\x1a\x1c.telemetry.TelemetryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYREQUEST']._serialized_start=30
  _globals['_TELEMETRYREQUEST']._serialized_end=110
  _globals['_TELEMETRYRESPONSE']._serialized_start=112
  _globals['_TELEMETRYRESPONSE']._serialized_end=147
  _globals['_TELEMETRY']._serialized_start=149
  _globals['_TELEMETRY']._serialized_end=236
# @@protoc_insertion_point(module_scope)
